- test/k8s_sandbox/test_sandbox.py
There is a new requirement in Inspect's `SandboxEnvironment.read_file()`
>When reading text files, implementations should preserve newline constructs (e.g. crlf should be preserved not converted to lf).
https://github.com/UKGovernmentBEIS/inspect_ai/blob/bcf7bd58d083073e79a078172887e08341211426/src/inspect_ai/util/_sandbox/environment.py#L205C1-L208C1
This was already the case for the K8s sandbox provider. I've just added a test to prevent any regressions now that this is documented.
> The `read_file()` function should should preserve newline constructs (e.g. crlf should be preserved not converted to lf). This is equivalent to specifying `newline=""` in a call to the Python `open()` function.
> Add test verifying that line endings are maintained for `read_file()`

- docs/docs/design/limitations.md
In some legacy Docker-based evals, users were modifying the `/etc/hosts` file in their `Dockerfile` to e.g. make `website.com` resolve to `127.0.0.1`. This does not work with our built-in Helm chart due to the CoreDNS sidecar.
Even if we didn't have the sidecar, this is not recommended https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/#why-does-kubelet-manage-the-hosts-file
> Document the fact that changes to `/etc/hosts` will be trampled over

- docs/docs/design/complexities.md
- docs/docs/helm/built-in-chart.md
* Document why we chose a DNS-based approach over using `HostAliases` (which edits `/etc/hosts`). Off the back of #42 
* Explicitly state that  `dnsRecord: true` is required.
* Fix some minor formatting issues (see commit messages).
> Document DNS-based approach rationale + fix formatting

- CHANGELOG.md
- docs/docs/tips/debugging-k8s-sandboxes.md
- docs/docs/tips/troubleshooting.md
- poetry.lock
- pyproject.toml
- src/k8s_sandbox/_helm.py
- src/k8s_sandbox/_logger.py
- src/k8s_sandbox/_pod/executor.py
- src/k8s_sandbox/_sandbox_environment.py
- test/k8s_sandbox/conftest.py
- test/k8s_sandbox/inspect_integration/testing_utils/utils.py
The `SANDBOX` log level was removed when the `TRACE` log level and associated functionality ([docs](https://inspect.ai-safety-institute.org.uk/tracing.html)) was added to Inspect ([PR](https://github.com/UKGovernmentBEIS/inspect_ai/pull/1038)).
JJ recommended ([Slack](https://inspectcommunity.slack.com/archives/C0801K3CEN8/p1735832232725649?thread_ts=1735262148.252489&cid=C0801K3CEN8)) using:
* `trace_action()` for any long running tasks that we'd like the lifecycle logged of (so in our case, Helm install/uninstall and Pod ops like `exec()`)
* `trace_message()` for any other informational logging which used to be at `SANDBOX` log level (like listing Pods, or logging `exec()` results)
It is great that these logs will be automatically captured. Though there will be some added friction of …
> `SANDBOX` log level deprecation

- CHANGELOG.md
- src/k8s_sandbox/_helm.py
- src/k8s_sandbox/_manager.py
- src/k8s_sandbox/_sandbox_environment.py
- test/k8s_sandbox/inspect_integration/test_cleanup.py
Users often ask how to do this, and we normally have to share a command like `helm list -q | xargs -P 10 helm uninstall`.
Note that the [docs recommend](https://k8s-sandbox.ai-safety-institute.org.uk/getting-started/remote-cluster/#recommendations) setting up your cluster such that each user has their own namespace to reduce the risk of a careless user uninstalling someone else's Helm charts.
https://github.com/user-attachments/assets/03a02564-f4a2-40ff-a823-a01f97abdc5d
See issue #7.
See [Inspect's docs](https://inspect.ai-safety-institute.org.uk/sandboxing.html#environment-cleanup) on this command.
> Add support for `inspect sandbox cleanup k8s`

- src/k8s_sandbox/resources/helm/agent-env/templates/network-policy.yaml
Housekeeping: whilst considering an update to Cilium on our cluster, I realised the CNP descriptions were a bit inconsistent and out of date wrt supporting `allowCIDR` and `allowEntities`.
> Improve Cilium Network Policy descriptions

- test/diagnostics/network-issues/README.md
- test/diagnostics/network-issues/helm-values.yaml
- test/diagnostics/network-issues/main.py
- test/diagnostics/network-issues/run.py
- test/diagnostics/network-issues/test_can_run_diagnostic.py
As suggested by Jason, let's put this script somewhere such that we can easily refer back to it and share with others. I haven't included the results as these are quite specific to our infrastructure at the time of running the tests and were not done in a particularly well controlled environment.
It will be run at a very small scale as part of CI just to prevent regressions in the script. I don't believe we'll get meaningful data from trying to run this at scale in CI:
1. We're heavily limited on how many concurrent deployments we can have on the default GitHub runner
2. There are no cluster-wide Cilium Network Policies (CNP) on our Minikube cluster (which we think were a contributor to the issues)
I've created an issue to better document our findings #29 and recommendations for CNPs.
> Add networking diagnostic test

- CHANGELOG.md
- src/k8s_sandbox/_helm.py
The `quiet` parameter of `uninstall()` is designed to work the same was as the [Docker Compose implementation](https://github.com/UKGovernmentBEIS/inspect_ai/blob/main/src/inspect_ai/util/_sandbox/docker/compose.py#L42) in Inspect - the idea being that the user shouldn't see `helm uninstall` output in most cases (except if they ran `inspect sandbox cleanup k8s` or the eval was cancelled/errored).
Users have previously shared logs or screenshots of `RuntimeError: Helm uninstall failed. {"release": "bmkvavf7", "result": "not captured"}`. Usually this is a red herring ([documented here](https://k8s-sandbox.ai-safety-institute.org.uk/tips/troubleshooting/#im-seeing-helm-uninstall-failed-errors)) but the "not captured" bit is unhelpful. The reason the `helm uninstall` output was not captured …
> Always capture `helm uninstall` output so that errors contain meaningful info

- docs/docs/design/limitations.md
This was prompted by a discussion on an [Inspect PR](https://github.com/UKGovernmentBEIS/inspect_ai/pull/1107)
I've gathered the exceptions recorded in the issues of this repo https://github.com/UKGovernmentBEIS/inspect_k8s_sandbox/issues?q=is%3Aissue+is%3Aopen+label%3A%223rd+party+errors%22
And explained the rationale for not retrying upon seeing these exceptions.
> Document certain "known" exceptions and why we don't retry `exec()` commands

- CHANGELOG.md
- docs/docs/helm/built-in-chart.md
- src/k8s_sandbox/resources/helm/agent-env/templates/services.yaml
- test/k8s_sandbox/helm_chart/resources/cluster-default-runtime-values.yaml
- test/k8s_sandbox/helm_chart/resources/unset-runtime-class-values.yaml
- test/k8s_sandbox/helm_chart/test_helm_chart.py
- test/k8s_sandbox/resources/runtime-class-values.yaml
- test/k8s_sandbox/test_runtime_class.py
We've been heavily opinionated that gVisor should be the container runtime of choice, but users can always override it if needed. However, you must override it to some non-null value. We'd like to add an escape hatch for users who wish to use their cluster's default runtime. We generally don't recommend taking this approach as this makes evals portable (now documented on docs site).
See Slack discussion https://inspectcommunity.slack.com/archives/C0855KJ6BMW/p1736847936476909
> Add `unset` magic string for runtimeClassName

- .github/workflows/format.yml
- .github/workflows/lint.yml
- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- src/k8s_sandbox/__init__.py
These were copied from another repo originally. There are some ignores (E203: whitespace-before-punctuation) which we don't need to ignore.
And we _do_ want to be strict on the `D10x` (missing docstrings in public members) rules within `src` but not within `test`.
> Tighten Ruff rules

- CHANGELOG.md
- src/k8s_sandbox/_kubernetes_api.py
'namespace' is often not explicitly included in context entries and the convention here is to target 'default'. In order to repro this, try creating a cluster with `kind` then using it to spawn a sandbox, and you'll get an exception due to the explicit lookup of a namespace.
> Handle the case where namespace isn't specified, and default to 'default'

- CHANGELOG.md
- docs/docs/design/limitations.md
- docs/docs/getting-started/remote-cluster.md
- docs/docs/security/network-access.md
- src/k8s_sandbox/resources/helm/agent-env/Chart.yaml
- src/k8s_sandbox/resources/helm/agent-env/README.md
- src/k8s_sandbox/resources/helm/agent-env/templates/network-policy.yaml
- test/k8s_sandbox/test_network_policy.py
- test/k8s_sandbox/test_networks.py
Please see the `### DNS Exfiltration` docs section added in this PR for the motivation.
I'll advertise the following changes in behaviour to users:
1. Only DNS lookups to services part of the eval and any `allowedDomains` are permitted.
2. Reverse DNS lookups (i.e. IP address to domain name) are no longer permitted.
3. Requests to domains which aren't on the allow list will now typically fail more quickly with "temporary failure in DNS resolution" or similar rather than a long timeout (this depends on the client used though).
I've done some validation against UK AISI evals (I'll discuss this internally).
> Prevent DNS exfiltration attacks

- poetry.lock
- test/k8s_sandbox/test_inspect_self_check.py
The `test_write_file_without_permissions` test has been split into 2, causing this test to fail against the latest version of Inspect.
* `test_write_text_file_without_permissions`
* `test_write_binary_file_without_permissions`
> Update skipped Inspect `self_check` tests

- CHANGELOG.md
- docs/docs/tips/troubleshooting.md
- src/k8s_sandbox/_helm.py
- test/k8s_sandbox/test_helm.py
A get a lot of support queries about "INSTALLATION FAILED: context deadline exceeded". We have docs on this, so I'd like to make it easier to users to refer to them (and discover them).
I'm also conscious that almost all of UK AISI's k8s usage is on a cluster which auto scales node groups, so I've made the docs more general to also encompass this.
> Improve helm install timeout error message

- CHANGELOG.md
- docs/docs/tips/troubleshooting.md
- src/k8s_sandbox/_helm.py
- test/k8s_sandbox/test_helm.py
When a helm release fails to **install** (e.g. user cancelled, timeout, resource quotas etc.), we'll error the sample and Inspect will then ask us to clean up that sample, so we'll attempt to **uninstall** the Helm release. I think this is the correct behaviour - we should not assume that a `helm install` failing means that the release isn't at least "partially" installed.
However, this results in a lot of error messages which users have become desensitised to. In amongst these "helm uninstall ... release not found" errors are sometimes different messages like `Error: failed to delete release: xxx` where we legitimately failed to uninstall an existing release.
> Ignore "release not found" errors during helm uninstall

- CHANGELOG.md
- src/k8s_sandbox/_helm.py
5 minutes is the default for Helm which is why we adopted it.
It is a balancing act between increasing this to allow time for pulling large images and cluster autoscaling versus reducing it so that errors (e.g. incorrect image name, container keeps crashing, readiness probe will never pass) are caught without a long delay.
On balance, I think 10 minutes is more appropriate, especially for clusters which auto-scale node groups.
I welcome disagreement - but our users are generally asking for this, so as long as it is for sound, explainable reasons, we can push back.
> Bump default Helm install (and uninstall) timeout from 5 to 10 minutes

- poetry.lock
- src/k8s_sandbox/_helm.py
The return type of Inspect's `concurrency()` has changed, therefore mypy complains.
This only affects type-checking, doesn't have any bearing on running evals, therefore this change is forward & backward compatible.
> Update inspect_ai, resolve type checking issue

- README.md
- src/k8s_sandbox/_helm.py
The docs are now at https://k8s-sandbox.aisi.org.uk
Once the Inspect docs site is updated, we should update the links here too.
> Update docs URLs for k8s-sandbox.aisi.org.uk

- CHANGELOG.md
- docs/docs/tips/configuration.md
- src/k8s_sandbox/_helm.py
- src/k8s_sandbox/_kubernetes_api.py
- src/k8s_sandbox/_manager.py
- src/k8s_sandbox/_pod/op.py
- src/k8s_sandbox/_pod/pod.py
- src/k8s_sandbox/_sandbox_environment.py
- test/k8s_sandbox/inspect_integration/custom_chart/test_integration.py
- test/k8s_sandbox/inspect_integration/test_cleanup.py
- test/k8s_sandbox/test_config_validation.py
- test/k8s_sandbox/test_helm.py
- test/k8s_sandbox/utils.py
As requested by Sami.
This allows users to have a `Sample` target a specific cluster e.g. if a `Sample` requires GPU access and your primary cluster doesn't have suitable nodes. You can therefore be interacting with multiple clusters within the scope of a single eval / inspect process.
See #88
There are 2 considerations:
1. the Python `kubernetes` library is synchronous, so we use threads to parallelise usage of it
2. the kubeconfig file can change on disk between loading it and the Helm subprocess or kubernetes client using it
I've mitigated 1 by use of locks and thread locals.
For 2, as we're "telling" Helm which context _name_ to use (rather than e.g. passing it the immutable context dict itself), we'd have to take steps like creating a copy of the kubeconfig file on disk and having …
> Add support for specifying a kubeconfig context name

- CHANGELOG.md
- src/k8s_sandbox/_sandbox_environment.py
- test/k8s_sandbox/test_sandbox.py
- test/k8s_sandbox/utils.py
This is useful for human agent baselining or for providing users with a command to copy/paste to get a shell into the container.
This is not aimed at preventing METR implementing a method for doing this over SSH (as their human baseliners won't have cluster credentials) - it is simply aimed at ensuring the default method of creating a `SandboxConnection` is the vanilla `kubectl` option. We can definitely add alternative methods in future!
It is a bit janky as an error pops up despite command working - this may just be related to how we're using VS Code at AISI though (via SSH to EC2 instances).
Using Terminal:
https://github.com/user-attachments/assets/e9a2ff0c-1cca-47d1-95ee-f9e209b7821b
Using Window:
Sadly there's no way to specify the container name to connect to, or the kubeconfig …
> Implement `SandboxConnection`

- CHANGELOG.md
- src/k8s_sandbox/_sandbox_environment.py
- test/k8s_sandbox/test_sandbox.py
Not to be confused with similar #94 
`SandboxEnvironment.connection()` returns commands which the user can use to connect to a sandbox. Inspect PR https://github.com/UKGovernmentBEIS/inspect_ai/pull/1658 now adds an optional user parameter to this method.
> Support `user` parameter on `SandboxEnvironment.connection()`

- CHANGELOG.md
- docs/docs/design/limitations.md
- docs/docs/getting-started/prerequisites.md
- src/k8s_sandbox/_pod/error.py
- src/k8s_sandbox/_pod/execute.py
- src/k8s_sandbox/_pod/get_returncode.py
- src/k8s_sandbox/_pod/pod.py
- src/k8s_sandbox/_sandbox_environment.py
- test/k8s_sandbox/pod/test_get_returncode.py
- test/k8s_sandbox/test_inspect_self_check.py
- test/k8s_sandbox/test_sandbox.py
Use `runuser` to be able to `exec` commands as different users.
If any of the following occur, an error is raised which will cause the eval to fail (not just a failed ExecResult). The error message will include a link to the relevant docs.
- container not running as root
- container doesn't have `runuser`
- specified user doesn't exist
This is intentional as it is most likely a programming error/bug, not an LLM feeding in something silly.
See comment below on Inspect/Platform Infra discussion on this.
> Support `user` parameter on `SandboxEnvironment.exec()`

- src/k8s_sandbox/_sandbox_environment.py
- src/k8s_sandbox/compose/__init__.py
- src/k8s_sandbox/compose/_compose.py
- src/k8s_sandbox/compose/_converter.py
- test/k8s_sandbox/compose/test_converter.py
Sami at METR suggested we make these public as they're using them as part of their custom method of running Inspect evals. See the Slack thread for context: https://inspectcommunity.slack.com/archives/C080ET25C81/p1745475063114929?thread_ts=1744660848.641359&cid=C080ET25C81
Their rough implementation (copied from Slack) is:
```py
if k8s_sandbox._compose.compose.is_docker_compose_file(config_path):
sandbox_config = (
k8s_sandbox._compose.converter.convert_compose_to_helm_values(
config_path
)
)
else:
with config_path.open("r") as f:
sandbox_config = cast(dict[str, Any], yaml.load(f))  # 
```
As mentioned elsewhere in the Slack discussion, we were considering adding a callback to `K8sSandboxEnvironmentConfig` to allow eval authors to transform the generated `helm-values.yaml` (e.g. for …
> Export `is_docker_compose_file()` and `convert_compose_to_helm_values()`

- src/k8s_sandbox/compose/_converter.py
- test/k8s_sandbox/compose/test_converter.py
Docker compose byte values (i.e. memory) are allowed to be a fractional value. Fortunately, so are Kubernetes `resource.Quantity`s.
This PR just adds this to the regexp in `_converter.convert_unit()` and adds a single test.
> Support fractional byte values

- CHANGELOG.md
- src/k8s_sandbox/compose/_converter.py
- test/k8s_sandbox/compose/test_converter.py
See discussion here re swebench https://github.com/UKGovernmentBEIS/inspect_evals/issues/212#issuecomment-2896690871
From the Inspect docs:
>The ctf-agent-environment is not an image that exists on a remote registry, so we add the x-local: true to indicate that it should not be pulled. If local images are tagged, they also will not be pulled by default (so x-local: true is not required).
For k8s, we always pull images. We'll emit a warning if `x-local: true`, and silently ignore it if it is any other value.
> Ignore `x-local` key when converting from Compose to Helm values

- pyproject.toml
- src/k8s_sandbox/_manager.py
Disappointing bug which got through to production, noticed by Alex. Was a missing required `context_name=None` argument in a call to `uninstall()`.
My first reaction is "mypy should have caught this". But it wasn't because
a) the return type of the function containing the error was not defined (should have been `-> None`)
b) we don't run mypy with `--strict` or have `check_untyped_defs` set
I've resolved both in this PR.
Sadly tests do not cover this precise code path (they do cover other parts of the function though). This is because such a test would involve uninstalling all Helm releases in a namespace, and a user can run tests against the production cluster so I thought it would be unwise to actually try to perform this action just by running `pytest`. In a more mature system, I'd add …
> Add missing `context_name` arg, prevent similar issues in future

- src/k8s_sandbox/resources/helm/agent-env/templates/helpers/_helpers.tpl
- test/k8s_sandbox/helm_chart/test_helm_chart.py
Sorry, #105 doesn't work when there's more than one label specified in `values.yaml`. This PR fixes the underlying issue. The problem was, the template removed whitespace between each label in the list of labels in `agentEnv.labelsFromValues`.
I've added tests for this case.
I've also tested this manually, with this `values.yaml`:
```yaml
additionalResources: ["apiVersion: cilium.io/v2\nkind: CiliumNetworkPolicy\nmetadata:\n\
\  name: {{ template \"agentEnv.fullname\" $ }}-sandbox-default-external-ingress\n\
\  annotations:\n    {{- toYaml $.Values.annotations | nindent 6 }}\nspec:\n \
\ description: |\n    Allow external ingress from all entities to the default
service on port 2222.\n  endpointSelector:\n    matchLabels:\n      io.kubernetes.pod.namespace:
{{ $.Release.Namespace }}\n …
```
> Fix Helm template rendering with multiple labels

- src/k8s_sandbox/resources/helm/agent-env/README.md
- src/k8s_sandbox/resources/helm/agent-env/templates/services.yaml
- src/k8s_sandbox/resources/helm/agent-env/values.schema.json
- src/k8s_sandbox/resources/helm/agent-env/values.yaml
- test/k8s_sandbox/helm_chart/test_helm_chart.py
We ran into issues with getting rate limited by docker hub when trying to pull the coredns image as our cluster scaled up real fast. One way around this is to authenticate image pulls, getting unlimited rate limit. There are Reasons why that's a bit more complicated for us than just adding an image pull secret, and IMO one should be able to configure the coredns image being used anyway (e.g. pull your own hardened image from your internal registry), so I added that functionality.
> Allow configuring coredns image and command

- src/k8s_sandbox/_helm.py
- test/k8s_sandbox/test_helm.py
We've started running each of our jobs in separate namespaces for isolation, which we create as part of a helm release that creates the job which runs `inspect eval-set`. However, since we also run multiple clusters, which the inspect processes chooses between based on properties of the task, that namespace would not exist in the _other_ cluster (the one that's not where the `inspect eval-set` job is running). This gives you an option to create that namespace as needed.
> Add option to create namespace on helm install

- src/k8s_sandbox/resources/helm/agent-env/templates/services.yaml
The inspect k8s plugin documentation [currently states that](https://k8s-sandbox.aisi.org.uk/helm/built-in-chart/#resource-requests-and-limits):
> Default resource limits are assigned for each service within the Helm chart. The limits and requests are equal such that the Pods have a Guaranteed [QoS class](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/).
This is not actually true at the moment though, because the `coredns` service has a lower requests than limits: https://github.com/UKGovernmentBEIS/inspect_k8s_sandbox/blob/7ec705f967e598a96d8a9d0cd809bca5a014ceae/src/k8s_sandbox/resources/helm/agent-env/templates/services.yaml#L105-L115
Per the [k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assi …
> Increase coredns resource requests to match limits to ensure Guaranteed QoS
